sudo: required

env:
  global:
    - BRANCH=$TRAVIS_BRANCH
    - NAMESPACE=default

script:
  - echo $BRANCH

deploy:
  - provider: script
    script: bash ./deploy.sh testing
    on:
      branch: develop
  - provider: script
    script: bash ./deploy.sh production
    on:
      branch: master
  - provider: script
    script: bash ./deploy.sh staging
    on:
      branch: staging